
const initial_data = {
      "id": "",
      "mfl_code": null,
      "name": "",
      "county": "",
      "sub_county": "",
      "owner": "",
      "lat": null,
      "lon": null,
      "partner": "",
      "agency": "",
      "emr_site": false,
      "non_emr_site": false,
      "asal": false,
      "pepfar": false,
      "infrastructure_type": "",
      "KEPH_Level": "",
      "CT": false,
      "HTS": false,
      "IL": false,
      "mHealth": false,
      "KP":false,
      "ovc_offered": null,
      "otz_offered": null,
      "tb_offered": null,
      "prep_offered": null,
      "mnch_offered": null,
      "kp_offered": null,
      "lab_man_offered": null,
      "hiv_offered": null, 
      "tpt_offered": null, 
      "covid_19_offered": null, 
      "evmmc_offered": null,
      "mhealth_ushauri": null,
      "mhealth_nishauri": null,
      "mhealth_c4c": null,
      "mhealth_mlab": null,
      "mhealth_psurvey": null,
      "mhealth_art": null,
      "il_status": null,
      "webADT_registration": null,
      "webADT_pharmacy": null,
      "il_three_PM": null,
      "il_air": null,
      "il_ushauri": null,
      "il_mlab": null,
      "il_lab_manifest": null, 
      "il_nimeconfirm": null,
      "emr_type": null,
      "emr_status": null,
      "mode_of_use":null,
      "date_of_emr_impl":null,
      "hts_use": null,
      "hts_deployment": null,
      "hts_status": null
    }

    export default initial_data
