
const initial_data = {
      "id": "",
      "mfl_code": null,
      "name": "",
      "county": 30,
      "sub_county": null,
      "owner": "",
      "lat": null,
      "lon": null,
      "partner": "",
      "agency": "",
      "CT": false,
      "HTS": false,
      "IL": false,
      "ovc_offered": null,
      "otz_offered": null,
      "tb_offered": null,
      "prep_offered": null,
      "mnch_offered": null,
      "kp_offered": null,
      "lab_man_offered": null,
      "mhealth_ushauri": null,
      "mhealth_nishauri": null,
      "mhealth_c4c": null,
      "mhealth_mlab": null,
      "mhealth_psurvey": null,
      "mhealth_art": null,
      "il_status": null,
      "webADT_registration": null,
      "webADT_pharmacy": null,
      "il_three_PM": null,
      "il_air": null,
      "il_ushauri": null,
      "il_mlab": null,
      "emr_type": null,
      "emr_status": null,
      "hts_use": null,
      "hts_deployment": null,
      "hts_status": null
    }

    export default initial_data
  