name: deploy to production
on:
  push:
    branches: [ cicd ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/dwh-his-frontend      
          cd /apps/github-workflows/dwh-his-frontend
          git pull origin master
          git status
          cp /apps/dockerApps/dwh-his-frontend/Dockerfile /apps/github-workflows/dwh-his-frontend
          cp /apps/dockerApps/dwh-his-frontend/default.conf /apps/github-workflows/dwh-his-frontend
          cp /apps/dockerApps/dwh-his-frontend/nginx.conf /apps/github-workflows/dwh-his-frontend
          cp /apps/dockerApps/dwh-his-frontend/.env /apps/github-workflows/dwh-his-frontend
          cp -r /apps/dockerApps/dwh-his-frontend/ssl/ /apps/github-workflows/dwh-his-frontend
          docker stop dwhisfrontend
          docker rm dwhisfrontend
          docker build -t dwhisfrontend .
          docker run -d --name=dwhisfrontend --restart always -p 3838:443 dwhisfrontend:latest

