name: remote ssh command
on:
  push:
    branches: [ cicd ]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/dwh-his-frontend      
          cd /apps/github-workflows/dwh-his-frontend
          git pull origin master
          git status
